version: 0.2

phases:
  install:
    commands:
      - apk --no-cache add zip
  pre_build:
    commands:
      - cp -r /home/a ../
  build:
    commands:
      - composer install
      - zip -r archive-${CODEBUILD_SOURCE_VERSION}.zip ./
#  post_build:

artifacts:
  files:
    - archive-${CODEBUILD_SOURCE_VERSION}.zip